#pragma once

#define CVARIABLE(...) 
#define CDIAPER(...) 

// 代码反射宏
#define CODE_REFLECTOR_MACRO_INNER(A,B,C,D) A##B##C##D
#define CODE_REFLECTOR_MACRO(A,B,C,D) CODE_REFLECTOR_MACRO_INNER(A,B,C,D)
#define CODEREFLECTION(...) \
CODE_REFLECTOR_MACRO(CURRENT_FILE_ID_BT,_,NewLine,_GENERATED_BODY_BT)
